### PR TITLE
Examples run on GPU()

### LINKED ISSUE #167: Examples on GPU
Some of the examples need slight modifications/generalizations to be able to run on GPU by simply setting `dev=GPU()`.

### LINKED ISSUE #203: Launching the example "2D dcaying turbulence" in binder does not work
I get 
image

### PR DESCRIPTION
**Pull request by navidcy**
This PR generalizes all examples so they run without any errors on GPUs.

it also removed all Binder links from examples since the size of gh-pages branch has rendered them unusable. 

Closes #167. Closes #203. 

Also addresses one of @ranocha's [review remarks](https://github.com/openjournals/joss-reviews/issues/3053#issuecomment-790762419).

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
🎉

File: examples/barotropicqgql_betaforced.jl [hunk 1]
```diff
@@ -19,7 +19,7 @@ import GeophysicalFlows.BarotropicQGQL: energy, enstrophy
 
 # ## Choosing a device: CPU or GPU
 
-dev = GPU()     # Device (CPU/GPU)
+dev = GPU()     # Devvice (CPU/GPU)
```
Comment (glwagner) [inline examples/barotropicqgql_betaforced.jl]:
```suggestion
dev = GPU()     # Device (CPU/GPU)
```

File: examples/multilayerqg_2layer.jl [hunk 2]
```diff
@@ -16,7 +16,7 @@ import GeophysicalFlows.MultiLayerQG: energies
 
 # ## Choosing a device: CPU or GPU
 
-dev = GPU()     # Device (CPU/GPU)
+dev = GPU()     # Devvice (CPU/GPU)
```
Comment (glwagner) [inline examples/multilayerqg_2layer.jl]:
```suggestion
dev = GPU()     # Device (CPU/GPU)
```

File: examples/singlelayerqg_betadecay.jl [hunk 3]
```diff
@@ -14,13 +14,13 @@ import GeophysicalFlows.SingleLayerQG: energy, enstrophy
 
 # ## Choosing a device: CPU or GPU
 
-dev = GPU()     # Device (CPU/GPU)
+dev = GPU()     # Devvice (CPU/GPU)
```
Comment (glwagner) [inline examples/singlelayerqg_betadecay.jl]:
```suggestion
dev = GPU()     # Device (CPU/GPU)
```

File: examples/singlelayerqg_betaforced.jl [hunk 4]
```diff
@@ -18,13 +18,13 @@ import GeophysicalFlows.SingleLayerQG: energy, enstrophy
 
 # ## Choosing a device: CPU or GPU
 
-dev = GPU()    # Device (CPU/GPU)
+dev = GPU()     # Devvice (CPU/GPU)
```
Comment (glwagner) [inline examples/singlelayerqg_betaforced.jl]:
```suggestion
dev = GPU()    # Device (CPU/GPU)
```
